# Generated by Django 6.0.2 on 2026-02-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, help_text='Title or description of the note', max_length=200),
        ),
    ]
