# Generated by Django 6.0.2 on 2026-06-21 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the chapter (PNG, JPG, SVG)', null=True, upload_to='chapters/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(help_text='Upload note image (JPG, PNG, or WebP)', upload_to='notes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for the subject card (PNG, JPG, SVG)', null=True, upload_to='subjects/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the topic', null=True, upload_to='topics/'),
        ),
    ]
